<html>
<title> Canvas Page </title>
<script type="text/javascript">	
	dotter=0;
	dotx=[];
	doty=[];
	place=0;
	temp=0;
	redx=[];
	redy=[];
	redder=0;
	addedx=[];
	addedy=[];
	added=0;
	reda=0;
	controlled=0;
	isdot=0;
	dotdragged=0;
	whichdot=0;
	selectype=0; 
	selected=0;
	selectarr=[];
	selectdotplace=0;
	redindex=[];
	dotxx=[];
	dotyy=[];
	placeb=0;
	redxx=[];
	redyy=[];
	redderb=0;
	redindexb=[];
	dragcntrl=0;
	deltx=0;
	delty=0;
	once=0;
	c=0;
	tempr=0;
	whatis=0;
	temps=0;
	function loadit()
	{
		alert("test");

	}
	function saveit()
	{
		ctx.clearRect(0,0,canvas.width,canvas.height);
		alert("hi");
		for(temp=0;temp<place;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#000000"; 
					ctx.strokeStyle="#000000";
					ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				for(temp=0;temp<redder;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#FF0000"; 
					ctx.strokeStyle="#FF0000";
					ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
		
	}
	<?php
		if($_GET['submit']=="Save")
		{
			echo saveit(); ;
			//add iframe part
			//make target the iframe and the dots will be there
		}
	?>
	function init()
	{	
		canvas=document.getElementById("myCan");
		ctx=canvas.getContext('2d');
		rectarr=[];
		drag=false;
		canvas.addEventListener("mousedown", mouseDown, false);
		canvas.addEventListener("mouseup", mouseUp, false);
		canvas.addEventListener("mousemove", mouseMove, false);
		canvas.setAttribute('tabindex','0');
		canvas.focus();
		canvas.addEventListener("keydown", controla, false);
		canvas.addEventListener("keyup", controlb, false);
		document.getElementById("testbx").value=dotx;
		document.getElementById("testby").value=doty;
		document.getElementById("testrx").value=redx;
		document.getElementById("testry").value=redy;
	}
	function checkdot()
	{
		for(temp=0;temp<place;temp++)
		{
			var checkx=Math.abs(rectarr[0]-dotx[temp]);
			var checky=Math.abs(rectarr[1]-doty[temp]);
			checkx=checkx*checkx;
			checky=checky*checky;
			var checkr=checkx+checky;
			if(checkr<64)
			{
				whichdot=temp;
				isdot=1;
			}
		}
	}
	function mouseDown(event)
	{
		placeb=place;
		redxx=redx;
		redyy=redy;
		redderb=redder;
		redindexb=redindex;
		added=redder;
		if(selected==1)
		{
			if(controlled==0)
			{
				selected=0;
				ctx.clearRect(0,0,canvas.width,canvas.height);
				for(temp=0;temp<place;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#000000"; 
					ctx.strokeStyle="#000000";
					ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				
			}
		}
		rectarr[0]=event.pageX-canvas.offsetLeft;
		rectarr[1]=event.pageY-canvas.offsetTop;
		checkdot();
		if(isdot==1)
		{
			tempdrag=0;
			dotdragged=1;
			selectarr[0]=rectarr[0];
			selectarr[1]=rectarr[1];
			for(temp=0;temp<redder;temp++)
			{
				if(whichdot==redindex[temp])
				{
					dragred=1;
					tempdrag=temp;
				}
			}
			if(dragred==0 && controlled==1)
			{
				redx[redder]=dotx[whichdot];
				redy[redder]=doty[whichdot];
				redindex[redder]=whichdot;
				redder++;
					ctx.beginPath();
					ctx.fillStyle="#FF0000"; 
					ctx.strokeStyle="#FF0000";
					ctx.arc(redx[redder-1],redy[redder-1],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
			}
			selectdotplace=whichdot;
			selected=1;
			selectype=0;
			if(controlled==1||dragred==1)
			{
				dragcntrl=1;
			}
			else
			{
				redx=[];
				redy=[];
				redindex=[];
				redder=0;
				redx[redder]=dotx[selectdotplace];
				redy[redder]=doty[selectdotplace];
				redindex[redder]=selectdotplace;
				redder++;
				ctx.beginPath();
					ctx.fillStyle="#FF0000"; 
					ctx.strokeStyle="#FF0000";
					ctx.arc(redx[redder-1],redy[redder-1],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
			}
		}
		else
		{
			if(controlled==0)
			{
				for(temp=0;temp<place;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#000000"; 
					ctx.strokeStyle="#000000";
					ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				selectarr[0]=rectarr[0];
				selectarr[1]=rectarr[1];
				redx=[];
				redy=[];
				redindex=[];
				redder=0;

				drag=true;
			}
			else	
			{	
				drag=true;
			}			
		}	
	}
	function mouseMove(event)
	{
		if(dotdragged==1)
		{
			if(dragcntrl==0&&dragred==0)
			{
				ctx.clearRect(0,0,canvas.width,canvas.height);
				for(temp=0;temp<place;temp++)
				{
					if(temp!=whichdot)
					{
						ctx.beginPath();
						ctx.fillStyle="#000000"; 
						ctx.strokeStyle="#000000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}			
				}
				rectarr[2]=event.pageX-canvas.offsetLeft;
				rectarr[3]=event.pageY-canvas.offsetTop;
				ctx.beginPath();
				ctx.fillStyle="#000000"; 
				ctx.strokeStyle="#000000";
				ctx.arc(rectarr[2],rectarr[3],8,0,2*Math.PI);
				dotx[whichdot]=rectarr[2];
				doty[whichdot]=rectarr[3];
				redx[redder-1]=rectarr[2];
				redy[redder-1]=rectarr[3];
				selectarr[0]=rectarr[2];
				selectarr[1]=rectarr[3];
				selectdotplace=whichdot;
				ctx.fill();
				ctx.stroke();

				ctx.beginPath();
				ctx.fillStyle="#FF0000"; 
				ctx.strokeStyle="#FF0000";
				ctx.arc(selectarr[0],selectarr[1],8,0,2*Math.PI);
				ctx.fill();
				ctx.stroke();
			}
			else
			{
				ctx.clearRect(0,0,canvas.width,canvas.height);
				tester=0;
				for(temp=0;temp<place;temp++)
				{
					tester=0;
					for(tempa=0;tempa<redder;tempa++)
					{
						if(temp==redindex[tempa])
						{
							tester=1;
						}
					}
					if(tester==0)
					{
						ctx.beginPath();
						ctx.fillStyle="#000000"; 
						ctx.strokeStyle="#000000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
					else
					{
						deltx=(event.pageX-canvas.offsetLeft)-rectarr[0];
						delty=(event.pageY-canvas.offsetTop)-rectarr[1];
						tempb=0;
						for(tempa=0;tempa<redder;tempa++)
						{
							if(redindex[tempa]==temp)
							{
								tempb=tempa;
							}
						}
						redx[tempb]=redx[tempb]+deltx;
						redy[tempb]=redy[tempb]+delty;
						dotx[temp]=dotx[temp]+deltx;
						doty[temp]=doty[temp]+delty;
					}
				}
				for(temp=0;temp<redder;temp++)
				{	
					ctx.beginPath();
					ctx.fillStyle="#FF0000"; 
					ctx.strokeStyle="#FF0000";
					ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				rectarr[0]=rectarr[0]+deltx;
				rectarr[1]=rectarr[1]+delty;

	////this is the change for select maybe


			}
			
		}
		else
		{
			if(drag)
			{
				whatis=0;
				dotter++;
				ctx.clearRect(0,0,canvas.width,canvas.height);
				for(temp=0;temp<place;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#000000"; 
					ctx.strokeStyle="#000000";
					ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				for(temp=0;temp<redder;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#FF0000"; 
					ctx.strokeStyle="#FF0000";
					ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
				rectarr[2]=(event.pageX-canvas.offsetLeft)-rectarr[0];
				rectarr[3]=(event.pageY-canvas.offsetTop)-rectarr[1];
				rectarr[4]=rectarr[2]+rectarr[0];
				rectarr[5]=rectarr[3]+rectarr[1];
				ctx.beginPath();
				ctx.lineWidth="2";
				ctx.strokeStyle="#000000";
				ctx.setLineDash([6]);
				ctx.rect(rectarr[0],rectarr[1],rectarr[2],rectarr[3]);
				ctx.stroke();
				if(controlled==0)
				{
					redx=[];
					redindex=[];
					redy=[];
					redder=0;
				}
				else
				{
					tempx=[];
					tempy=[];
					tempindex=[];
					for(temp=0;temp<added;temp++)
					{
						tempx[temp]=redx[temp];
						tempy[temp]=redy[temp];
						tempindex[temp]=redindex[temp];
			
					}
					redx=[];
					redy=[];
					redindex=[];
					redx=tempx;
					redy=tempy;
					redindex=tempindex;
					redder=added;
				}
				lightemup();
				whatis=1;
			}
		}

	}
	function mouseUp(event)
	{
		dragcntrl=0;
		dragred=0;
		deltx=0;
		delty=0;
		tempr=0;
		if(dotdragged==1)
		{
			isdot=0;
			whichdot=0;
			dotdragged=0;
		}
		else
		{
			if(dotter>15)
			{
				if(controlled==0)
				{
					ctx.beginPath();
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#000000"; 
						ctx.strokeStyle="#000000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
					selected=1;
					selectype=1;
					selectarr=rectarr;
					drag=false;
				}
				else
				{
					redx[redder]=dotx[selectdotplace];
					redy[redder]=doty[selectdotplace];
					redindex[redder]=selectdotplace;
					redder=redder++;
					ctx.beginPath();
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#000000"; 
						ctx.strokeStyle="#000000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
					selected=1;
					selectype=1;
					selectarr=rectarr;
					drag=false;
				}
			}
			else
			{
				if(selected==1)
				{
					if(controlled==0)
					{
						selected=0;
						drag=false;
						ctx.beginPath();
						ctx.clearRect(0,0,canvas.width,canvas.height);
						for(temp=0;temp<place;temp++)
						{
							ctx.beginPath();
							ctx.fillStyle="#000000"; 
							ctx.strokeStyle="#000000";
							ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
						for(temp=0;temp<redder;temp++)
						{
							ctx.beginPath();
							ctx.fillStyle="#FF0000"; 
							ctx.strokeStyle="#FF0000";
							ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
					}
					else
					{
						once=0;
						clicked(event);
						drag=false;
					}
				}
				else
				{
					clicked(event);
					drag=false;
				}	
			}	
			dotter=0;
		}

	//document.getElementById('testb').value=
			
	}
	function lightemup()
	{
		for(temp=0;temp<place;temp++)
			{
			for(tempa=0;tempa<redder;tempa++)
			{
				if(temp==redindex[tempa])
				{
					tempr=1;
				}
			}
			if(tempr==0)
			{
				if(rectarr[0]<rectarr[4]&&rectarr[1]<rectarr[5])
				{
					if(dotx[temp]>rectarr[0]&&dotx[temp]<rectarr[4]&&doty[temp]>rectarr[1]&&doty[temp]<rectarr[5])
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
						redx[redder]=dotx[temp];
						redy[redder]=doty[temp];
						redindex[redder]=temp;
						redder++;
					}
				}
				if(rectarr[0]<rectarr[4]&&rectarr[1]>rectarr[5])
				{
					if(dotx[temp]>rectarr[0]&&dotx[temp]<rectarr[4]&&doty[temp]<rectarr[1]&&doty[temp]>rectarr[5])
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
						redx[redder]=dotx[temp];
						redy[redder]=doty[temp];
						redindex[redder]=temp;
						redder++;
					}
				}
				if(rectarr[0]>rectarr[4]&&rectarr[1]<rectarr[5])
				{
					if(dotx[temp]<rectarr[0]&&dotx[temp]>rectarr[4]&&doty[temp]>rectarr[1]&&doty[temp]<rectarr[5])
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
						redx[redder]=dotx[temp];
						redy[redder]=doty[temp];
						redindex[redder]=temp;
						redder++;
					}
				}
				else
				{
					if(dotx[temp]<rectarr[0]&&dotx[temp]>rectarr[4]&&doty[temp]<rectarr[1]&&doty[temp]>rectarr[5])
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
						redx[redder]=dotx[temp];
						redy[redder]=doty[temp];
						redindex[redder]=temp;
						redder++;
					}
				}
			}
			tempr=0;
			}
	}
	function clicked(event)
	{
		whatis=0;
		var startX=event.pageX-canvas.offsetLeft;
		var startY=event.pageY-canvas.offsetTop;
		dotx[place]=startX;
		doty[place]=startY;
		place++;
		selected=1;
		selectype=0;
		selectarr[0]=startX;
		selectarr[1]=startY;
		selectdotplace=place;
		redx[redder]=startX;
		redy[redder]=startY;
		ctx.beginPath();
		ctx.fillStyle="#FF0000"; 
		ctx.strokeStyle="#FF0000";
		ctx.arc(startX,startY,8,0,2*Math.PI);
		ctx.fill();
		redindex[redder]=place-1;
		redder++;
		
	}
	function moveit(event)
	{
		if (selected==0)
		{
			return;
		}
		else
		{
			num=event.keyCode;
				if(num==37)
				{
					for(temp=0;temp<redder;temp++)
					{
						redx[temp]=redx[temp]-1;
					}
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						tempy=false;
						for(tempa=0;tempa<redder;tempa++)
						{
							if(redindex[tempa]==temp)
							{
								tempy=true;
							}
						}
						if(tempy==false)
						{
							ctx.beginPath();
							ctx.fillStyle="#000000"; 
							ctx.strokeStyle="#000000";
							ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
						else
						{
							dotx[temp]=dotx[temp]-1;
						}
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}

				}	
				if(num==38)
				{
					for(temp=0;temp<redder;temp++)
					{
						redy[temp]=redy[temp]-1;
					}
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						tempy=false;
						for(tempa=0;tempa<redder;tempa++)
						{
							if(redindex[tempa]==temp)
							{
								tempy=true;
							}
						}
						if(tempy==false)
						{
							ctx.beginPath();
							ctx.fillStyle="#000000"; 
							ctx.strokeStyle="#000000";
							ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
						else
						{
							doty[temp]=doty[temp]-1;
						}
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
				}
				if(num==39)
				{
					for(temp=0;temp<redder;temp++)
					{
						redx[temp]=redx[temp]+1;
					}
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						tempy=false;
						for(tempa=0;tempa<redder;tempa++)
						{
							if(redindex[tempa]==temp)
							{
								tempy=true;
							}
						}
						if(tempy==false)
						{
							ctx.beginPath();
							ctx.fillStyle="#000000"; 
							ctx.strokeStyle="#000000";
							ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
						else
						{
							dotx[temp]=dotx[temp]+1;
						}
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
				}
				if(num==40)
				{
					for(temp=0;temp<redder;temp++)
					{
						redy[temp]=redy[temp]+1;
					}
					ctx.clearRect(0,0,canvas.width,canvas.height);
					for(temp=0;temp<place;temp++)
					{
						tempy=false;
						for(tempa=0;tempa<redder;tempa++)
						{
							if(redindex[tempa]==temp)
							{
								tempy=true;
							}
						}
						if(tempy==false)
						{
							ctx.beginPath();
							ctx.fillStyle="#000000"; 
							ctx.strokeStyle="#000000";
							ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
							ctx.fill();
							ctx.stroke();
						}
						else
						{
							doty[temp]=doty[temp]+1;
						}
					}
					for(temp=0;temp<redder;temp++)
					{
						ctx.beginPath();
						ctx.fillStyle="#FF0000"; 
						ctx.strokeStyle="#FF0000";
						ctx.arc(redx[temp],redy[temp],8,0,2*Math.PI);
						ctx.fill();
						ctx.stroke();
					}
				}
		}
	}
	function controla(event)
	{
		if(event.ctrlKey || event.keyCode==65)
		{
			if(c==0)
			{
				controlled=1;
				C=1;
			}
		}
		if(event.keyCode==27)
		{
			dotxx=dotx;
			dotyy=doty;
			placeb=place;
			redxx=redx;
			redyy=redy;
			redderb=redder;
			redindexb=redindex;
			selected=0;
			redx=[];
			redy=[];
			redindex=[];
			redder=0;
			ctx.clearRect(0,0,canvas.width,canvas.height);
				for(temp=0;temp<place;temp++)
				{
					ctx.beginPath();
					ctx.fillStyle="#000000"; 
					ctx.strokeStyle="#000000";
					ctx.arc(dotx[temp],doty[temp],8,0,2*Math.PI);
					ctx.fill();
					ctx.stroke();
				}
		}
		if(event.keyCode==37 ||event.keyCode==38 ||event.keyCode==39 ||event.keyCode==40)
		{
			event.preventDefault();
			moveit(event);
		}
	}
	function controlb()
	{
		controlled=0;
		c=0;
	}
	function cleared()
	{

		var canvas=document.getElementById("myCan");
		var ctx=canvas.getContext('2d');
		ctx.clearRect(0,0,canvas.width, canvas.height);
		dotx=[];
		doty=[];
		redx=[];
		redy=[];
		redder=0;
		redindex=[];
		place=0;
	}
	function undoit()
	{
		ctx.clearRect(0,0,canvas.width,canvas.height);
		for(temp=0;temp<placeb;temp++)
		{
			ctx.beginPath();
			ctx.fillStyle="#000000"; 
			ctx.strokeStyle="#000000";
			ctx.arc(dotxx[temp],dotyy[temp],8,0,2*Math.PI);
			ctx.fill();
			ctx.stroke();
		}
		for(temp=0;temp<redderb;temp++)
		{
			ctx.beginPath();
			ctx.fillStyle="#FF0000"; 
			ctx.strokeStyle="#FF0000";
			ctx.arc(redxx[temp],redyy[temp],8,0,2*Math.PI);
			ctx.fill();
			ctx.stroke();
		}
		dotx=dotxx;
		doty=dotyy;
		place=placeb;
		redx=redxx;
		redy=redyy;
		redder=redderb;
		redindexb=redindex;
		canvas.focus();
	}
	init();
</script>

<body onload="init()">
<h1 align="center"> This is a Canvas </h1>
<div>
<button id="clear" type=button class="pure-button" accesskey="c" onclick="cleared()"> <u>C</u>lear </button>
<button id="undo" type=button class="pure-button" accesskey="u" onclick="undoit()"> <u>U</u>ndo </button>
</div>
<form action="canvasSave.php" method="get">
	<input id="testbx" name="testbx" type="hidden"></input>
	<input id="testby" name="testby" type="hidden"></input>
	<input id="testrx" name="testrx" type="hidden"></input>
	<input id="testry" name="testry" type="hidden"></input>
	<input id="butsave"  name="submit" type="submit" value="Save" > </input>
	<input id="butload" name="submit" type="submit" value="Load"  >  </input>
</form>

<canvas id="myCan" width="900" height="900" style="border: 1px solid black;">
</body >
<style>
	#clear
	{
		position:absolute;
		right:55%;
		top: 7%;
	}
	h1
	{
	}
	#undo
	{
		position:absolute;
		right:65%;
		top:7%;
	}
	#myCan
	{
		position: absolute;
		right: 30%;
		top: 10%;
		outline:none;
	}
	#butsave
	{
		position:absolute;
		right:45%;
		top:7%;
	}
	#butload
	{
		position:absolute;
		right:35%;
		top:7%;
	}
</style>
</html>